import { AutomationRule } from "./types";

export type AutomationRulePreset = Omit<
  AutomationRule,
  "id" | "isActive" | "lastTriggered"
>;

export const automationPresets: AutomationRulePreset[] = [
  {
    name: "BTC 15m Mean Reversion",
    symbol: "BTC/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 2,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.5,
    takeProfitPct: 5.0,
    trailingStopPct: 1.5,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "BTC 1h Trend Continuation",
    symbol: "BTC/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 5,
    amountType: "percent",
    minScore: 15,
    stopLossPct: 3.5,
    takeProfitPct: 7.5,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "BTC 4h Trend Strength",
    symbol: "BTC/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 6,
    amountType: "percent",
    minScore: 22,
    stopLossPct: 4.0,
    takeProfitPct: 12.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 240,
  },
  {
    name: "BTC 1d Macro Trend",
    symbol: "BTC/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 3,
    amountType: "percent",
    minScore: 25,
    stopLossPct: 6.0,
    takeProfitPct: 18.0,
    trailingStopPct: 4.0,
    cooldownMinutes: 720,
  },
  {
    name: "BTC 15m Mean Reversion Exit",
    symbol: "BTC/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "BTC 1h Trend Exhaustion",
    symbol: "BTC/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -15,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "BTC 4h Trend Reversal",
    symbol: "BTC/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -22,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "BTC 1d Macro Risk-Off",
    symbol: "BTC/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -27,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "ETH 15m Mean Reversion",
    symbol: "ETH/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 2,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.5,
    takeProfitPct: 5.0,
    trailingStopPct: 1.5,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "ETH 1h Trend Continuation",
    symbol: "ETH/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 5,
    amountType: "percent",
    minScore: 15,
    stopLossPct: 3.5,
    takeProfitPct: 7.5,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "ETH 4h Trend Strength",
    symbol: "ETH/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 6,
    amountType: "percent",
    minScore: 22,
    stopLossPct: 4.0,
    takeProfitPct: 12.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 240,
  },
  {
    name: "ETH 1d Macro Trend",
    symbol: "ETH/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 3,
    amountType: "percent",
    minScore: 25,
    stopLossPct: 6.0,
    takeProfitPct: 18.0,
    trailingStopPct: 4.0,
    cooldownMinutes: 720,
  },
  {
    name: "ETH 15m Mean Reversion Exit",
    symbol: "ETH/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "ETH 1h Trend Exhaustion",
    symbol: "ETH/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -15,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "ETH 4h Trend Reversal",
    symbol: "ETH/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -22,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "ETH 1d Macro Risk-Off",
    symbol: "ETH/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -27,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "BNB 15m Mean Reversion",
    symbol: "BNB/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 2,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.5,
    takeProfitPct: 5.0,
    trailingStopPct: 1.5,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "BNB 1h Trend Continuation",
    symbol: "BNB/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 5,
    amountType: "percent",
    minScore: 15,
    stopLossPct: 3.5,
    takeProfitPct: 7.5,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "BNB 4h Trend Strength",
    symbol: "BNB/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 6,
    amountType: "percent",
    minScore: 22,
    stopLossPct: 4.0,
    takeProfitPct: 12.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 240,
  },
  {
    name: "BNB 1d Macro Trend",
    symbol: "BNB/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 3,
    amountType: "percent",
    minScore: 25,
    stopLossPct: 6.0,
    takeProfitPct: 18.0,
    trailingStopPct: 4.0,
    cooldownMinutes: 720,
  },
  {
    name: "BNB 15m Mean Reversion Exit",
    symbol: "BNB/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "BNB 1h Trend Exhaustion",
    symbol: "BNB/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -15,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "BNB 4h Trend Reversal",
    symbol: "BNB/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -22,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "BNB 1d Macro Risk-Off",
    symbol: "BNB/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -27,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "SOL 15m Mean Reversion",
    symbol: "SOL/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "SOL 1h Trend Continuation",
    symbol: "SOL/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "SOL 4h Trend Strength",
    symbol: "SOL/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "SOL 1d Macro Trend",
    symbol: "SOL/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "SOL 15m Mean Reversion Exit",
    symbol: "SOL/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "SOL 1h Trend Exhaustion",
    symbol: "SOL/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "SOL 4h Trend Reversal",
    symbol: "SOL/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "SOL 1d Macro Risk-Off",
    symbol: "SOL/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "XRP 15m Mean Reversion",
    symbol: "XRP/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "XRP 1h Trend Continuation",
    symbol: "XRP/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "XRP 4h Trend Strength",
    symbol: "XRP/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "XRP 1d Macro Trend",
    symbol: "XRP/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "XRP 15m Mean Reversion Exit",
    symbol: "XRP/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "XRP 1h Trend Exhaustion",
    symbol: "XRP/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "XRP 4h Trend Reversal",
    symbol: "XRP/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "XRP 1d Macro Risk-Off",
    symbol: "XRP/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "ADA 15m Mean Reversion",
    symbol: "ADA/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "ADA 1h Trend Continuation",
    symbol: "ADA/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "ADA 4h Trend Strength",
    symbol: "ADA/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "ADA 1d Macro Trend",
    symbol: "ADA/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "ADA 15m Mean Reversion Exit",
    symbol: "ADA/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "ADA 1h Trend Exhaustion",
    symbol: "ADA/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "ADA 4h Trend Reversal",
    symbol: "ADA/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "ADA 1d Macro Risk-Off",
    symbol: "ADA/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "DOGE 15m Mean Reversion",
    symbol: "DOGE/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "DOGE 1h Trend Continuation",
    symbol: "DOGE/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "DOGE 4h Trend Strength",
    symbol: "DOGE/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "DOGE 1d Macro Trend",
    symbol: "DOGE/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "DOGE 15m Mean Reversion Exit",
    symbol: "DOGE/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "DOGE 1h Trend Exhaustion",
    symbol: "DOGE/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "DOGE 4h Trend Reversal",
    symbol: "DOGE/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "DOGE 1d Macro Risk-Off",
    symbol: "DOGE/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "MATIC 15m Mean Reversion",
    symbol: "MATIC/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "MATIC 1h Trend Continuation",
    symbol: "MATIC/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "MATIC 4h Trend Strength",
    symbol: "MATIC/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "MATIC 1d Macro Trend",
    symbol: "MATIC/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "MATIC 15m Mean Reversion Exit",
    symbol: "MATIC/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "MATIC 1h Trend Exhaustion",
    symbol: "MATIC/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "MATIC 4h Trend Reversal",
    symbol: "MATIC/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "MATIC 1d Macro Risk-Off",
    symbol: "MATIC/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "DOT 15m Mean Reversion",
    symbol: "DOT/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "DOT 1h Trend Continuation",
    symbol: "DOT/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "DOT 4h Trend Strength",
    symbol: "DOT/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "DOT 1d Macro Trend",
    symbol: "DOT/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "DOT 15m Mean Reversion Exit",
    symbol: "DOT/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "DOT 1h Trend Exhaustion",
    symbol: "DOT/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "DOT 4h Trend Reversal",
    symbol: "DOT/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "DOT 1d Macro Risk-Off",
    symbol: "DOT/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
  {
    name: "AVAX 15m Mean Reversion",
    symbol: "AVAX/USDT",
    timeframe: "15m",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 1.5,
    amountType: "percent",
    minScore: 10,
    stopLossPct: 2.0,
    takeProfitPct: 4.5,
    trailingStopPct: 1.0,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\"<\",\"val\":30},{\"indicator\":\"CCI\",\"op\":\"<\",\"val\":-100},{\"indicator\":\"MFI\",\"op\":\"<\",\"val\":20},{\"indicator\":\"WILLR\",\"op\":\"<\",\"val\":-80}]}",
  },
  {
    name: "AVAX 1h Trend Continuation",
    symbol: "AVAX/USDT",
    timeframe: "1h",
    side: "buy",
    triggerType: "signal",
    signalType: "BUY",
    amount: 3,
    amountType: "percent",
    minScore: 14,
    stopLossPct: 3.0,
    takeProfitPct: 7.0,
    trailingStopPct: 2.0,
    cooldownMinutes: 90,
  },
  {
    name: "AVAX 4h Trend Strength",
    symbol: "AVAX/USDT",
    timeframe: "4h",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 4,
    amountType: "percent",
    minScore: 20,
    stopLossPct: 3.5,
    takeProfitPct: 10.0,
    trailingStopPct: 2.5,
    cooldownMinutes: 240,
  },
  {
    name: "AVAX 1d Macro Trend",
    symbol: "AVAX/USDT",
    timeframe: "1d",
    side: "buy",
    triggerType: "signal",
    signalType: "STRONG_BUY",
    amount: 2.5,
    amountType: "percent",
    minScore: 23,
    stopLossPct: 5.0,
    takeProfitPct: 15.0,
    trailingStopPct: 3.0,
    cooldownMinutes: 720,
  },
  {
    name: "AVAX 15m Mean Reversion Exit",
    symbol: "AVAX/USDT",
    timeframe: "15m",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 30,
    amountType: "percent",
    minScore: -10,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 288,
    cooldownMinutes: 30,
    conditions: "{\"operator\":\"AND\",\"rules\":[{\"indicator\":\"RSI\",\"op\":\">\",\"val\":70},{\"indicator\":\"CCI\",\"op\":\">\",\"val\":100},{\"indicator\":\"MFI\",\"op\":\">\",\"val\":80},{\"indicator\":\"WILLR\",\"op\":\">\",\"val\":-20}]}",
  },
  {
    name: "AVAX 1h Trend Exhaustion",
    symbol: "AVAX/USDT",
    timeframe: "1h",
    side: "sell",
    triggerType: "signal",
    signalType: "SELL",
    amount: 40,
    amountType: "percent",
    minScore: -14,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 72,
    cooldownMinutes: 90,
  },
  {
    name: "AVAX 4h Trend Reversal",
    symbol: "AVAX/USDT",
    timeframe: "4h",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 60,
    amountType: "percent",
    minScore: -20,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 18,
    cooldownMinutes: 240,
  },
  {
    name: "AVAX 1d Macro Risk-Off",
    symbol: "AVAX/USDT",
    timeframe: "1d",
    side: "sell",
    triggerType: "signal",
    signalType: "STRONG_SELL",
    amount: 100,
    amountType: "percent",
    minScore: -25,
    stopLossPct: 0,
    takeProfitPct: 0,
    trailingStopPct: 0,
    onlyIfInPosition: true,
    reduceOnly: true,
    minProfitPct: 0.5,
    breakEvenAfterPct: 1.0,
    maxHoldBars: 3,
    cooldownMinutes: 720,
  },
];
