from __future__ import annotations

from typing import Protocol


class ConnectorProtocol(Protocol):
    def get_or_create_thread(self, sender: str) -> str: ...

    def reset_thread(self, sender: str) -> str: ...

    def run_turn(self, thread_id: str, prompt: str, *, timeout_seconds: int | None = None) -> str: ...

    def ensure_started(self) -> None: ...

    def shutdown(self) -> None: ...
